export const testUser = {
    steamid: "76561199447872275",
    displayName: "Babaka",
    level: 27,
    avatar: "https://avatars.steamstatic.com/669ba94a7cc1ebc74fadbf447bfaca007cf4b636_full.jpg",
    profileUrl:
        "https://steamcommunity.com/profiles/76561199447872275/",
    lastlogoff: 1756636520,
    onlineStatus: 1,
    country: "UA",
    timeCreated: 1671903195,
    friends: [
        {
            steamid: "76561198015895061",
            displayName: '"UAB" ĮMONĖ lol3000',
            avatar: "https://avatars.steamstatic.com/9d59a333a61e7758c1fc02aa68d29e7af468bc5a_full.jpg",
            profileUrl: "https://steamcommunity.com/id/hhfgff/",
            onlineStatus: 0,
        },
        {
            steamid: "76561199224183542",
            displayName: "Purple",
            avatar: "https://avatars.steamstatic.com/9a74194adfb1439a267e2868f291d9d59f9f1e55_full.jpg",
            profileUrl:
                "https://steamcommunity.com/profiles/76561199224183545/",
            onlineStatus: 0,
        },
        {
            steamid: "76561198374376543",
            displayName: "RubyRoseUwU",
            avatar: "https://avatars.steamstatic.com/78488061cca73d071ad4bcc1a086ef9b65f8f050_full.jpg",
            profileUrl:
                "https://steamcommunity.com/profiles/76561198374376541/",
            onlineStatus: 0,
        },
        {
            steamid: "76561199501817134",
            displayName: "Valapple",
            avatar: "https://avatars.steamstatic.com/6a6b34636c03b91b3094b5749f9d005858ca6b28_full.jpg",
            profileUrl:
                "https://steamcommunity.com/profiles/76561199501817133/",
            onlineStatus: 0,
        },
        {
            steamid: "76561199207624125",
            displayName: "ヴァルバラ",
            avatar: "https://avatars.steamstatic.com/8fd07256b6cfb1da3540875d9283350a3dc9ae2f_full.jpg",
            profileUrl:
                "https://steamcommunity.com/profiles/76561199207624129/",
            onlineStatus: 0,
        },
        {
            steamid: "76561199763743356",
            displayName: "БрайанФимозер",
            avatar: "https://avatars.steamstatic.com/9a39889c7f72500c239dd0098f883f868133f440_full.jpg",
            profileUrl:
                "https://steamcommunity.com/profiles/76561199763743352/",
            onlineStatus: 1,
        },
        {
            steamid: "76561198015895067",
            displayName: '"UAB" ĮMONĖ lol3000',
            avatar: "https://avatars.steamstatic.com/9d59a333a61e7758c1fc02aa68d29e7af468bc5a_full.jpg",
            profileUrl: "https://steamcommunity.com/id/hhfgff/",
            onlineStatus: 0,
        },
        {
            steamid: "76561199224183548",
            displayName: "Purple",
            avatar: "https://avatars.steamstatic.com/9a74194adfb1439a267e2868f291d9d59f9f1e55_full.jpg",
            profileUrl:
                "https://steamcommunity.com/profiles/76561199224183545/",
            onlineStatus: 0,
        },
        {
            steamid: "76561198374376549",
            displayName: "RubyRoseUwU",
            avatar: "https://avatars.steamstatic.com/78488061cca73d071ad4bcc1a086ef9b65f8f050_full.jpg",
            profileUrl:
                "https://steamcommunity.com/profiles/76561198374376541/",
            onlineStatus: 0,
        },
        {
            steamid: "76561199501817130",
            displayName: "Valapple",
            avatar: "https://avatars.steamstatic.com/6a6b34636c03b91b3094b5749f9d005858ca6b28_full.jpg",
            profileUrl:
                "https://steamcommunity.com/profiles/76561199501817133/",
            onlineStatus: 0,
        },
        {
            steamid: "765611992076241211",
            displayName: "ヴァルバラ",
            avatar: "https://avatars.steamstatic.com/8fd07256b6cfb1da3540875d9283350a3dc9ae2f_full.jpg",
            profileUrl:
                "https://steamcommunity.com/profiles/76561199207624129/",
            onlineStatus: 0,
        },
        {
            steamid: "765611997637433512",
            displayName: "БрайанФимозер",
            avatar: "https://avatars.steamstatic.com/9a39889c7f72500c239dd0098f883f868133f440_full.jpg",
            profileUrl:
                "https://steamcommunity.com/profiles/76561199763743352/",
            onlineStatus: 1,
        },
        {
            steamid: "765611980158950613",
            displayName: '"UAB" ĮMONĖ lol3000',
            avatar: "https://avatars.steamstatic.com/9d59a333a61e7758c1fc02aa68d29e7af468bc5a_full.jpg",
            profileUrl: "https://steamcommunity.com/id/hhfgff/",
            onlineStatus: 0,
        },
        {
            steamid: "765611992241835414",
            displayName: "Purple",
            avatar: "https://avatars.steamstatic.com/9a74194adfb1439a267e2868f291d9d59f9f1e55_full.jpg",
            profileUrl:
                "https://steamcommunity.com/profiles/76561199224183545/",
            onlineStatus: 0,
        },
        {
            steamid: "765611983743765415",
            displayName: "RubyRoseUwU",
            avatar: "https://avatars.steamstatic.com/78488061cca73d071ad4bcc1a086ef9b65f8f050_full.jpg",
            profileUrl:
                "https://steamcommunity.com/profiles/76561198374376541/",
            onlineStatus: 0,
        },
        {
            steamid: "765611995018171316",
            displayName: "Valapple",
            avatar: "https://avatars.steamstatic.com/6a6b34636c03b91b3094b5749f9d005858ca6b28_full.jpg",
            profileUrl:
                "https://steamcommunity.com/profiles/76561199501817133/",
            onlineStatus: 0,
        },
        {
            steamid: "765611992076241217",
            displayName: "ヴァルバラ",
            avatar: "https://avatars.steamstatic.com/8fd07256b6cfb1da3540875d9283350a3dc9ae2f_full.jpg",
            profileUrl:
                "https://steamcommunity.com/profiles/76561199207624129/",
            onlineStatus: 0,
        },
        {
            steamid: "765611997637433518",
            displayName: "БрайанФимозер",
            avatar: "https://avatars.steamstatic.com/9a39889c7f72500c239dd0098f883f868133f440_full.jpg",
            profileUrl:
                "https://steamcommunity.com/profiles/76561199763743352/",
            onlineStatus: 1,
        },
        {
            steamid: "765611980158950619",
            displayName: '"UAB" ĮMONĖ lol3000',
            avatar: "https://avatars.steamstatic.com/9d59a333a61e7758c1fc02aa68d29e7af468bc5a_full.jpg",
            profileUrl: "https://steamcommunity.com/id/hhfgff/",
            onlineStatus: 0,
        },
        {
            steamid: "765611992241835420",
            displayName: "Purple",
            avatar: "https://avatars.steamstatic.com/9a74194adfb1439a267e2868f291d9d59f9f1e55_full.jpg",
            profileUrl:
                "https://steamcommunity.com/profiles/76561199224183545/",
            onlineStatus: 0,
        },
        {
            steamid: "765611983743765421",
            displayName: "RubyRoseUwU",
            avatar: "https://avatars.steamstatic.com/78488061cca73d071ad4bcc1a086ef9b65f8f050_full.jpg",
            profileUrl:
                "https://steamcommunity.com/profiles/76561198374376541/",
            onlineStatus: 0,
        },
        {
            steamid: "765611995018171322",
            displayName: "Valapple",
            avatar: "https://avatars.steamstatic.com/6a6b34636c03b91b3094b5749f9d005858ca6b28_full.jpg",
            profileUrl:
                "https://steamcommunity.com/profiles/76561199501817133/",
            onlineStatus: 0,
        },
        {
            steamid: "765611992076241223",
            displayName: "ヴァルバラ",
            avatar: "https://avatars.steamstatic.com/8fd07256b6cfb1da3540875d9283350a3dc9ae2f_full.jpg",
            profileUrl:
                "https://steamcommunity.com/profiles/76561199207624129/",
            onlineStatus: 0,
        },
        {
            steamid: "765611997637433524",
            displayName: "БрайанФимозер",
            avatar: "https://avatars.steamstatic.com/9a39889c7f72500c239dd0098f883f868133f440_full.jpg",
            profileUrl:
                "https://steamcommunity.com/profiles/76561199763743352/",
            onlineStatus: 1,
        },
        {
            steamid: "765611980158950625",
            displayName: '"UAB" ĮMONĖ lol3000',
            avatar: "https://avatars.steamstatic.com/9d59a333a61e7758c1fc02aa68d29e7af468bc5a_full.jpg",
            profileUrl: "https://steamcommunity.com/id/hhfgff/",
            onlineStatus: 0,
        },
        {
            steamid: "765611992241835426",
            displayName: "Purple",
            avatar: "https://avatars.steamstatic.com/9a74194adfb1439a267e2868f291d9d59f9f1e55_full.jpg",
            profileUrl:
                "https://steamcommunity.com/profiles/76561199224183545/",
            onlineStatus: 0,
        },
        {
            steamid: "765611983743765427",
            displayName: "RubyRoseUwU",
            avatar: "https://avatars.steamstatic.com/78488061cca73d071ad4bcc1a086ef9b65f8f050_full.jpg",
            profileUrl:
                "https://steamcommunity.com/profiles/76561198374376541/",
            onlineStatus: 0,
        },
        {
            steamid: "765611995018171328",
            displayName: "Valapple",
            avatar: "https://avatars.steamstatic.com/6a6b34636c03b91b3094b5749f9d005858ca6b28_full.jpg",
            profileUrl:
                "https://steamcommunity.com/profiles/76561199501817133/",
            onlineStatus: 0,
        },
        {
            steamid: "765611992076241229",
            displayName: "ヴァルバラ",
            avatar: "https://avatars.steamstatic.com/8fd07256b6cfb1da3540875d9283350a3dc9ae2f_full.jpg",
            profileUrl:
                "https://steamcommunity.com/profiles/76561199207624129/",
            onlineStatus: 0,
        },
        {
            steamid: "765611997637433530",
            displayName: "БрайанФимозер",
            avatar: "https://avatars.steamstatic.com/9a39889c7f72500c239dd0098f883f868133f440_full.jpg",
            profileUrl:
                "https://steamcommunity.com/profiles/76561199763743352/",
            onlineStatus: 1,
        },
    ],
    games: [
        {
            appid: 400,
            name: "Portal",
            playtimeForever: 112,
            playtimeWindowsForever: 112,
            playtimeMacForever: 0,
            playtimeLinuxForever: 0,
            playtimeDeckForever: 0,
            playtimeOffline: 0,
            lastTimePlayed: 1703982464,
            playtime2Weeks: 0,
            iconUrl:
                "https://media.steampowered.com/steamcommunity/public/images/apps/400/cfa928ab4119dd137e50d728e8fe703e4e970aff.jpg",
        },
        {
            appid: 12360,
            name: "FlatOut: Ultimate Carnage Collector's Edition",
            playtimeForever: 3238,
            playtimeWindowsForever: 3238,
            playtimeMacForever: 0,
            playtimeLinuxForever: 0,
            playtimeDeckForever: 0,
            playtimeOffline: 0,
            lastTimePlayed: 1734300318,
            playtime2Weeks: 0,
            iconUrl:
                "https://media.steampowered.com/steamcommunity/public/images/apps/12360/18e8998d43630ecf4bd26c252f10930d6b524e72.jpg",
        },
        {
            appid: 20900,
            name: "The Witcher: Enhanced Edition",
            playtimeForever: 61,
            playtimeWindowsForever: 61,
            playtimeMacForever: 0,
            playtimeLinuxForever: 0,
            playtimeDeckForever: 0,
            playtimeOffline: 0,
            lastTimePlayed: 1687026864,
            playtime2Weeks: 0,
            iconUrl:
                "https://media.steampowered.com/steamcommunity/public/images/apps/20900/746d1cd48fb2e57d579b05b6e9eccba95859e549.jpg",
        },
        {
            appid: 620,
            name: "Portal 2",
            playtimeForever: 686,
            playtimeWindowsForever: 686,
            playtimeMacForever: 0,
            playtimeLinuxForever: 0,
            playtimeDeckForever: 0,
            playtimeOffline: 0,
            lastTimePlayed: 1704398603,
            playtime2Weeks: 0,
            iconUrl:
                "https://media.steampowered.com/steamcommunity/public/images/apps/620/2e478fc6874d06ae5baf0d147f6f21203291aa02.jpg",
        },
        {
            appid: 105600,
            name: "Terraria",
            playtimeForever: 11417,
            playtimeWindowsForever: 11417,
            playtimeMacForever: 0,
            playtimeLinuxForever: 0,
            playtimeDeckForever: 0,
            playtimeOffline: 263,
            lastTimePlayed: 1755864404,
            playtime2Weeks: 3,
            iconUrl:
                "https://media.steampowered.com/steamcommunity/public/images/apps/105600/858961e95fbf869f136e1770d586e0caefd4cfac.jpg",
        },
        {
            appid: 20920,
            name: "The Witcher 2: Assassins of Kings Enhanced Edition",
            playtimeForever: 1556,
            playtimeWindowsForever: 1556,
            playtimeMacForever: 0,
            playtimeLinuxForever: 0,
            playtimeDeckForever: 0,
            playtimeOffline: 0,
            lastTimePlayed: 1689792529,
            playtime2Weeks: 0,
            iconUrl:
                "https://media.steampowered.com/steamcommunity/public/images/apps/20920/62dd5c627664df1bcabc47727c7dcd7ccab353e9.jpg",
        },
        {
            appid: 48000,
            name: "LIMBO",
            playtimeForever: 132,
            playtimeWindowsForever: 132,
            playtimeMacForever: 0,
            playtimeLinuxForever: 0,
            playtimeDeckForever: 0,
            playtimeOffline: 0,
            lastTimePlayed: 1686646220,
            playtime2Weeks: 0,
            iconUrl:
                "https://media.steampowered.com/steamcommunity/public/images/apps/48000/463f57855017564301b17050fba73804b3bd86d6.jpg",
        },
        {
            appid: 212500,
            name: "The Lord of the Rings Online™",
            playtimeForever: 0,
            playtimeWindowsForever: 0,
            playtimeMacForever: 0,
            playtimeLinuxForever: 0,
            playtimeDeckForever: 0,
            playtimeOffline: 0,
            lastTimePlayed: 0,
            playtime2Weeks: 0,
            iconUrl:
                "https://media.steampowered.com/steamcommunity/public/images/apps/212500/6dbff8345f6b3e5f092a834985c8f851859bfbf2.jpg",
        },
        {
            appid: 304430,
            name: "INSIDE",
            playtimeForever: 233,
            playtimeWindowsForever: 233,
            playtimeMacForever: 0,
            playtimeLinuxForever: 0,
            playtimeDeckForever: 0,
            playtimeOffline: 0,
            lastTimePlayed: 1686488812,
            playtime2Weeks: 0,
            iconUrl:
                "https://media.steampowered.com/steamcommunity/public/images/apps/304430/047e00c80d6aca008ce5eaaf54df4d98c822ee19.jpg",
        },
        {
            appid: 730,
            name: "Counter-Strike 2",
            playtimeForever: 82332,
            playtimeWindowsForever: 82332,
            playtimeMacForever: 0,
            playtimeLinuxForever: 0,
            playtimeDeckForever: 0,
            playtimeOffline: 61,
            lastTimePlayed: 1756651363,
            playtime2Weeks: 1607,
            iconUrl:
                "https://media.steampowered.com/steamcommunity/public/images/apps/730/8dbc71957312bbd3baea65848b545be9eae2a355.jpg",
        },
        {
            appid: 370660,
            name: "Opaline",
            playtimeForever: 105,
            playtimeWindowsForever: 105,
            playtimeMacForever: 0,
            playtimeLinuxForever: 0,
            playtimeDeckForever: 0,
            playtimeOffline: 0,
            lastTimePlayed: 1686053731,
            playtime2Weeks: 0,
            iconUrl:
                "https://media.steampowered.com/steamcommunity/public/images/apps/370660/c0474cd1d0ce9b2d615862687caa53aabac4673a.jpg",
        },
        {
            appid: 404790,
            name: "Godot Engine",
            playtimeForever: 1390,
            playtimeWindowsForever: 1390,
            playtimeMacForever: 0,
            playtimeLinuxForever: 0,
            playtimeDeckForever: 0,
            playtimeOffline: 1,
            lastTimePlayed: 1706737781,
            playtime2Weeks: 0,
            iconUrl:
                "https://media.steampowered.com/steamcommunity/public/images/apps/404790/057ae868c1d0975b941d73f58d1dc17c8a15a090.jpg",
        },
        {
            appid: 424840,
            name: "Little Nightmares",
            playtimeForever: 288,
            playtimeWindowsForever: 288,
            playtimeMacForever: 0,
            playtimeLinuxForever: 0,
            playtimeDeckForever: 0,
            playtimeOffline: 0,
            lastTimePlayed: 1686553404,
            playtime2Weeks: 0,
            iconUrl:
                "https://media.steampowered.com/steamcommunity/public/images/apps/424840/1904c041f963b5e2cb22b56c370444517cc4e288.jpg",
        },
        {
            appid: 489620,
            name: "Mini Thief Demo",
            playtimeForever: 0,
            playtimeWindowsForever: 0,
            playtimeMacForever: 0,
            playtimeLinuxForever: 0,
            playtimeDeckForever: 0,
            playtimeOffline: 0,
            lastTimePlayed: 0,
            playtime2Weeks: 0,
            iconUrl:
                "https://media.steampowered.com/steamcommunity/public/images/apps/489620/005b09dc1f3d4ee772ab20880ba9d304cca041fd.jpg",
        },
        {
            appid: 292030,
            name: "The Witcher 3: Wild Hunt",
            playtimeForever: 11357,
            playtimeWindowsForever: 11357,
            playtimeMacForever: 0,
            playtimeLinuxForever: 0,
            playtimeDeckForever: 0,
            playtimeOffline: 0,
            lastTimePlayed: 1703612888,
            playtime2Weeks: 0,
            iconUrl:
                "https://media.steampowered.com/steamcommunity/public/images/apps/292030/78d0ff98b67851f24539cdf2402cf147679134f4.jpg",
        },
        {
            appid: 533300,
            name: "Zup!",
            playtimeForever: 117,
            playtimeWindowsForever: 117,
            playtimeMacForever: 0,
            playtimeLinuxForever: 0,
            playtimeDeckForever: 0,
            playtimeOffline: 0,
            lastTimePlayed: 1687944866,
            playtime2Weeks: 0,
            iconUrl:
                "https://media.steampowered.com/steamcommunity/public/images/apps/533300/0d27b0e8358fb1de01df4be4f957548b196c7bba.jpg",
        },
        {
            appid: 552990,
            name: "World of Warships",
            playtimeForever: 0,
            playtimeWindowsForever: 0,
            playtimeMacForever: 0,
            playtimeLinuxForever: 0,
            playtimeDeckForever: 0,
            playtimeOffline: 0,
            lastTimePlayed: 0,
            playtime2Weeks: 0,
            iconUrl:
                "https://media.steampowered.com/steamcommunity/public/images/apps/552990/023b6bb5bcf82f9222d70cd38fdb18a899bd67e8.jpg",
        },
        {
            appid: 444200,
            name: "World of Tanks Blitz",
            playtimeForever: 28547,
            playtimeWindowsForever: 28547,
            playtimeMacForever: 0,
            playtimeLinuxForever: 0,
            playtimeDeckForever: 0,
            playtimeOffline: 17,
            lastTimePlayed: 1721855854,
            playtime2Weeks: 0,
            iconUrl:
                "https://media.steampowered.com/steamcommunity/public/images/apps/444200/6ce02840322f500c93a2f0304bc916fb44422631.jpg",
        },
        {
            appid: 563560,
            name: "Alien Swarm: Reactive Drop",
            playtimeForever: 145,
            playtimeWindowsForever: 145,
            playtimeMacForever: 0,
            playtimeLinuxForever: 0,
            playtimeDeckForever: 0,
            playtimeOffline: 0,
            lastTimePlayed: 1677592032,
            playtime2Weeks: 0,
            iconUrl:
                "https://media.steampowered.com/steamcommunity/public/images/apps/563560/3f30d5d196532aa1d79dbf133f067a38769178dc.jpg",
        },
        {
            appid: 588430,
            name: "Fallout Shelter",
            playtimeForever: 2478,
            playtimeWindowsForever: 2478,
            playtimeMacForever: 0,
            playtimeLinuxForever: 0,
            playtimeDeckForever: 0,
            playtimeOffline: 0,
            lastTimePlayed: 1756375128,
            playtime2Weeks: 280,
            iconUrl:
                "https://media.steampowered.com/steamcommunity/public/images/apps/588430/bb39b682fefd9a95486911cd991d8cdc5d7b57c9.jpg",
        },
        {
            appid: 601360,
            name: "Portal: Revolution",
            playtimeForever: 0,
            playtimeWindowsForever: 0,
            playtimeMacForever: 0,
            playtimeLinuxForever: 0,
            playtimeDeckForever: 0,
            playtimeOffline: 0,
            lastTimePlayed: 0,
            playtime2Weeks: 0,
            iconUrl:
                "https://media.steampowered.com/steamcommunity/public/images/apps/601360/7afb1feec3db22a42a34ac59657a510647ff4b77.jpg",
        },
        {
            appid: 617670,
            name: "Zup! S",
            playtimeForever: 253,
            playtimeWindowsForever: 253,
            playtimeMacForever: 0,
            playtimeLinuxForever: 0,
            playtimeDeckForever: 0,
            playtimeOffline: 0,
            lastTimePlayed: 1688311297,
            playtime2Weeks: 0,
            iconUrl:
                "https://media.steampowered.com/steamcommunity/public/images/apps/617670/64d8bf5ec2621eeace7f898afa9f56d6eb5aff4a.jpg",
        },
        {
            appid: 739630,
            name: "Phasmophobia",
            playtimeForever: 18874,
            playtimeWindowsForever: 18874,
            playtimeMacForever: 0,
            playtimeLinuxForever: 0,
            playtimeDeckForever: 0,
            playtimeOffline: 303,
            lastTimePlayed: 1755368804,
            playtime2Weeks: 0,
            iconUrl:
                "https://media.steampowered.com/steamcommunity/public/images/apps/739630/125673b382059f666ec81477173380a76e1df0be.jpg",
        },
        {
            appid: 860510,
            name: "Little Nightmares II",
            playtimeForever: 442,
            playtimeWindowsForever: 442,
            playtimeMacForever: 0,
            playtimeLinuxForever: 0,
            playtimeDeckForever: 0,
            playtimeOffline: 0,
            lastTimePlayed: 1685728434,
            playtime2Weeks: 0,
            iconUrl:
                "https://media.steampowered.com/steamcommunity/public/images/apps/860510/8875efb23a0fc1f079f227508d981f2cba82d735.jpg",
        },
        {
            appid: 939400,
            name: "LoveChoice",
            playtimeForever: 2,
            playtimeWindowsForever: 2,
            playtimeMacForever: 0,
            playtimeLinuxForever: 0,
            playtimeDeckForever: 0,
            playtimeOffline: 0,
            lastTimePlayed: 1694021335,
            playtime2Weeks: 0,
            iconUrl:
                "https://media.steampowered.com/steamcommunity/public/images/apps/939400/0b599cb9c44b0824ecdda766f59199315a932089.jpg",
        },
        {
            appid: 489520,
            name: "Minion Masters",
            playtimeForever: 0,
            playtimeWindowsForever: 0,
            playtimeMacForever: 0,
            playtimeLinuxForever: 0,
            playtimeDeckForever: 0,
            playtimeOffline: 0,
            lastTimePlayed: 0,
            playtime2Weeks: 0,
            iconUrl:
                "https://media.steampowered.com/steamcommunity/public/images/apps/489520/ad87d123224d786a413a6021ddaf9257e26c0a28.jpg",
        },
        {
            appid: 761890,
            name: "Albion Online",
            playtimeForever: 42914,
            playtimeWindowsForever: 42914,
            playtimeMacForever: 0,
            playtimeLinuxForever: 0,
            playtimeDeckForever: 0,
            playtimeOffline: 66,
            lastTimePlayed: 1754399995,
            playtime2Weeks: 0,
            iconUrl:
                "https://media.steampowered.com/steamcommunity/public/images/apps/761890/c58d1e42e59a9c6cc57c8da69d944b37ba45a0e2.jpg",
        },
        {
            appid: 1069740,
            name: "Seen",
            playtimeForever: 0,
            playtimeWindowsForever: 0,
            playtimeMacForever: 0,
            playtimeLinuxForever: 0,
            playtimeDeckForever: 0,
            playtimeOffline: 0,
            lastTimePlayed: 0,
            playtime2Weeks: 0,
            iconUrl:
                "https://media.steampowered.com/steamcommunity/public/images/apps/1069740/8da40e9bfb62086931281abf32e294ea91253099.jpg",
        },
        {
            appid: 379430,
            name: "Kingdom Come: Deliverance",
            playtimeForever: 415,
            playtimeWindowsForever: 415,
            playtimeMacForever: 0,
            playtimeLinuxForever: 0,
            playtimeDeckForever: 0,
            playtimeOffline: 0,
            lastTimePlayed: 1725531184,
            playtime2Weeks: 0,
            iconUrl:
                "https://media.steampowered.com/steamcommunity/public/images/apps/379430/915ec515c36645855abed0476b5b0891d8a4e47a.jpg",
        },
        {
            appid: 1215090,
            name: "My Friend is a Raven",
            playtimeForever: 21,
            playtimeWindowsForever: 21,
            playtimeMacForever: 0,
            playtimeLinuxForever: 0,
            playtimeDeckForever: 0,
            playtimeOffline: 0,
            lastTimePlayed: 1686647591,
            playtime2Weeks: 0,
            iconUrl:
                "https://media.steampowered.com/steamcommunity/public/images/apps/1215090/0288a37af66667dd0dd7866d759826bc2aec3b6e.jpg",
        },
        {
            appid: 1281930,
            name: "tModLoader",
            playtimeForever: 0,
            playtimeWindowsForever: 0,
            playtimeMacForever: 0,
            playtimeLinuxForever: 0,
            playtimeDeckForever: 0,
            playtimeOffline: 0,
            lastTimePlayed: 0,
            playtime2Weeks: 0,
            iconUrl:
                "https://media.steampowered.com/steamcommunity/public/images/apps/1281930/e8a125078a31b8475994e8ce4d8d6fdd6becc131.jpg",
        },
        {
            appid: 1151340,
            name: "Fallout 76",
            playtimeForever: 118,
            playtimeWindowsForever: 118,
            playtimeMacForever: 0,
            playtimeLinuxForever: 0,
            playtimeDeckForever: 0,
            playtimeOffline: 0,
            lastTimePlayed: 1733069556,
            playtime2Weeks: 0,
            iconUrl:
                "https://media.steampowered.com/steamcommunity/public/images/apps/1151340/81185120c1c1a4b26442828b25bbb58aec8d734c.jpg",
        },
        {
            appid: 1836200,
            name: "Fallout 76 Public Test Server",
            playtimeForever: 0,
            playtimeWindowsForever: 0,
            playtimeMacForever: 0,
            playtimeLinuxForever: 0,
            playtimeDeckForever: 0,
            playtimeOffline: 0,
            lastTimePlayed: 0,
            playtime2Weeks: 0,
            iconUrl:
                "https://media.steampowered.com/steamcommunity/public/images/apps/1836200/e153521098b536cc1ca5a79e03031533c44a6b05.jpg",
        },
        {
            appid: 1419170,
            name: "My Singing Monsters",
            playtimeForever: 24,
            playtimeWindowsForever: 24,
            playtimeMacForever: 0,
            playtimeLinuxForever: 0,
            playtimeDeckForever: 0,
            playtimeOffline: 0,
            lastTimePlayed: 1747650908,
            playtime2Weeks: 0,
            iconUrl:
                "https://media.steampowered.com/steamcommunity/public/images/apps/1419170/698d97ab021448d894c00eebc646323a8587ec96.jpg",
        },
        {
            appid: 1407200,
            name: "World of Tanks",
            playtimeForever: 0,
            playtimeWindowsForever: 0,
            playtimeMacForever: 0,
            playtimeLinuxForever: 0,
            playtimeDeckForever: 0,
            playtimeOffline: 0,
            lastTimePlayed: 0,
            playtime2Weeks: 0,
            iconUrl:
                "https://media.steampowered.com/steamcommunity/public/images/apps/1407200/fdedc7d172706ea39d2d2b389cd461cb4cbe7315.jpg",
        },
        {
            appid: 1443440,
            name: "Little Nightmares II Demo",
            playtimeForever: 0,
            playtimeWindowsForever: 0,
            playtimeMacForever: 0,
            playtimeLinuxForever: 0,
            playtimeDeckForever: 0,
            playtimeOffline: 0,
            lastTimePlayed: 0,
            playtime2Weeks: 0,
            iconUrl:
                "https://media.steampowered.com/steamcommunity/public/images/apps/1443440/8ef25028ecace8fcbb7dc7b5e8adfd49e8931e7f.jpg",
        },
        {
            appid: 1504980,
            name: "It Takes Two Friend's Pass",
            playtimeForever: 0,
            playtimeWindowsForever: 0,
            playtimeMacForever: 0,
            playtimeLinuxForever: 0,
            playtimeDeckForever: 0,
            playtimeOffline: 0,
            lastTimePlayed: 0,
            playtime2Weeks: 0,
            iconUrl:
                "https://media.steampowered.com/steamcommunity/public/images/apps/1504980/6b15f6d81c4fc52056f4928b363b7fac591a945b.jpg",
        },
        {
            appid: 582660,
            name: "Black Desert",
            playtimeForever: 0,
            playtimeWindowsForever: 0,
            playtimeMacForever: 0,
            playtimeLinuxForever: 0,
            playtimeDeckForever: 0,
            playtimeOffline: 0,
            lastTimePlayed: 0,
            playtime2Weeks: 0,
            iconUrl:
                "https://media.steampowered.com/steamcommunity/public/images/apps/582660/bf5ccace0a692720984827bf042143d0d4b28a42.jpg",
        },
        {
            appid: 578080,
            name: "PUBG: BATTLEGROUNDS",
            playtimeForever: 25376,
            playtimeWindowsForever: 25376,
            playtimeMacForever: 0,
            playtimeLinuxForever: 0,
            playtimeDeckForever: 0,
            playtimeOffline: 1,
            lastTimePlayed: 1754503754,
            playtime2Weeks: 0,
            iconUrl:
                "https://media.steampowered.com/steamcommunity/public/images/apps/578080/609f27278aa70697c13bf99f32c5a0248c381f9d.jpg",
        },
        {
            appid: 1955960,
            name: "HAWKED",
            playtimeForever: 0,
            playtimeWindowsForever: 0,
            playtimeMacForever: 0,
            playtimeLinuxForever: 0,
            playtimeDeckForever: 0,
            playtimeOffline: 0,
            lastTimePlayed: 0,
            playtime2Weeks: 0,
            iconUrl:
                "https://media.steampowered.com/steamcommunity/public/images/apps/1955960/7a9df41684f397d3d5f31ff8c4fce8010a7f6054.jpg",
        },
        {
            appid: 2139460,
            name: "Once Human",
            playtimeForever: 0,
            playtimeWindowsForever: 0,
            playtimeMacForever: 0,
            playtimeLinuxForever: 0,
            playtimeDeckForever: 0,
            playtimeOffline: 0,
            lastTimePlayed: 0,
            playtime2Weeks: 0,
            iconUrl:
                "https://media.steampowered.com/steamcommunity/public/images/apps/2139460/e1c29227c162232120c15edcf282df61ee35f091.jpg",
        },
        {
            appid: 1222670,
            name: "The Sims™ 4",
            playtimeForever: 0,
            playtimeWindowsForever: 0,
            playtimeMacForever: 0,
            playtimeLinuxForever: 0,
            playtimeDeckForever: 0,
            playtimeOffline: 0,
            lastTimePlayed: 0,
            playtime2Weeks: 0,
            iconUrl:
                "https://media.steampowered.com/steamcommunity/public/images/apps/1222670/ca6bc8b2411bce4a2cd325ab75f0204bc3a4ad98.jpg",
        },
        {
            appid: 660160,
            name: "Field of Glory II",
            playtimeForever: 0,
            playtimeWindowsForever: 0,
            playtimeMacForever: 0,
            playtimeLinuxForever: 0,
            playtimeDeckForever: 0,
            playtimeOffline: 0,
            lastTimePlayed: 0,
            playtime2Weeks: 0,
            iconUrl:
                "https://media.steampowered.com/steamcommunity/public/images/apps/660160/69e42fb6bde64f155cd5efc2f5c5a4642c18e9a4.jpg",
        },
        {
            appid: 1180660,
            name: "Tell Me Why",
            playtimeForever: 505,
            playtimeWindowsForever: 505,
            playtimeMacForever: 0,
            playtimeLinuxForever: 0,
            playtimeDeckForever: 0,
            playtimeOffline: 0,
            lastTimePlayed: 1686823775,
            playtime2Weeks: 0,
            iconUrl:
                "https://media.steampowered.com/steamcommunity/public/images/apps/1180660/6eb40e6f71226ce5bea75601a1ec0f9d6f647dd1.jpg",
        },
        {
            appid: 383270,
            name: "Hue",
            playtimeForever: 442,
            playtimeWindowsForever: 442,
            playtimeMacForever: 0,
            playtimeLinuxForever: 0,
            playtimeDeckForever: 0,
            playtimeOffline: 0,
            lastTimePlayed: 1685898807,
            playtime2Weeks: 0,
            iconUrl:
                "https://media.steampowered.com/steamcommunity/public/images/apps/383270/48682a5e83cf7f011a15b68f460a972635742d06.jpg",
        },
        {
            appid: 249050,
            name: "Dungeon of the ENDLESS™",
            playtimeForever: 0,
            playtimeWindowsForever: 0,
            playtimeMacForever: 0,
            playtimeLinuxForever: 0,
            playtimeDeckForever: 0,
            playtimeOffline: 0,
            lastTimePlayed: 0,
            playtime2Weeks: 0,
            iconUrl:
                "https://media.steampowered.com/steamcommunity/public/images/apps/249050/19f66db5192b05b71068dd243729c3d8b0d71f65.jpg",
        },
        {
            appid: 344740,
            name: "CRYPTARK",
            playtimeForever: 0,
            playtimeWindowsForever: 0,
            playtimeMacForever: 0,
            playtimeLinuxForever: 0,
            playtimeDeckForever: 0,
            playtimeOffline: 0,
            lastTimePlayed: 0,
            playtime2Weeks: 0,
            iconUrl:
                "https://media.steampowered.com/steamcommunity/public/images/apps/344740/c56bc2236cbcee87cab5c3d99e97be9f24d8cf50.jpg",
        },
        {
            appid: 2684660,
            name: "The Witcher 3 REDkit",
            playtimeForever: 0,
            playtimeWindowsForever: 0,
            playtimeMacForever: 0,
            playtimeLinuxForever: 0,
            playtimeDeckForever: 0,
            playtimeOffline: 0,
            lastTimePlayed: 0,
            playtime2Weeks: 0,
            iconUrl:
                "https://media.steampowered.com/steamcommunity/public/images/apps/2684660/c9c2c65a51b168c8387c72d641d892569587f65d.jpg",
        },
        {
            appid: 70,
            name: "Half-Life",
            playtimeForever: 66,
            playtimeWindowsForever: 66,
            playtimeMacForever: 0,
            playtimeLinuxForever: 0,
            playtimeDeckForever: 0,
            playtimeOffline: 0,
            lastTimePlayed: 1705179665,
            playtime2Weeks: 0,
            iconUrl:
                "https://media.steampowered.com/steamcommunity/public/images/apps/70/95be6d131fc61f145797317ca437c9765f24b41c.jpg",
        },
        {
            appid: 1035510,
            name: "Ultimate Zombie Defense",
            playtimeForever: 0,
            playtimeWindowsForever: 0,
            playtimeMacForever: 0,
            playtimeLinuxForever: 0,
            playtimeDeckForever: 0,
            playtimeOffline: 0,
            lastTimePlayed: 0,
            playtime2Weeks: 0,
            iconUrl:
                "https://media.steampowered.com/steamcommunity/public/images/apps/1035510/19ea5aca745585e84592011e0856661304167466.jpg",
        },
        {
            appid: 24010,
            name: "Train Simulator Classic 2024",
            playtimeForever: 2,
            playtimeWindowsForever: 2,
            playtimeMacForever: 0,
            playtimeLinuxForever: 0,
            playtimeDeckForever: 0,
            playtimeOffline: 0,
            lastTimePlayed: 1709931769,
            playtime2Weeks: 0,
            iconUrl:
                "https://media.steampowered.com/steamcommunity/public/images/apps/24010/689780210e97172c35c21d85b03a1b30a91bbbe5.jpg",
        },
        {
            appid: 383180,
            name: "Dead Island Riptide Definitive Edition",
            playtimeForever: 0,
            playtimeWindowsForever: 0,
            playtimeMacForever: 0,
            playtimeLinuxForever: 0,
            playtimeDeckForever: 0,
            playtimeOffline: 0,
            lastTimePlayed: 0,
            playtime2Weeks: 0,
            iconUrl:
                "https://media.steampowered.com/steamcommunity/public/images/apps/383180/68ea0c6d8ed1d089687da6318a62a7c3e3b5741b.jpg",
        },
        {
            appid: 235900,
            name: "RPG Maker XP",
            playtimeForever: 0,
            playtimeWindowsForever: 0,
            playtimeMacForever: 0,
            playtimeLinuxForever: 0,
            playtimeDeckForever: 0,
            playtimeOffline: 0,
            lastTimePlayed: 0,
            playtime2Weeks: 0,
            iconUrl:
                "https://media.steampowered.com/steamcommunity/public/images/apps/235900/d4fae8dbf49b2d8fda0aa9d74323529e41d200a2.jpg",
        },
        {
            appid: 1176710,
            name: "Space Crew: Legendary Edition",
            playtimeForever: 0,
            playtimeWindowsForever: 0,
            playtimeMacForever: 0,
            playtimeLinuxForever: 0,
            playtimeDeckForever: 0,
            playtimeOffline: 0,
            lastTimePlayed: 0,
            playtime2Weeks: 0,
            iconUrl:
                "https://media.steampowered.com/steamcommunity/public/images/apps/1176710/c1c0a0c7c7dae3525bc6a4bb07bc0bd69bc62ab0.jpg",
        },
        {
            appid: 282800,
            name: "100% Orange Juice",
            playtimeForever: 0,
            playtimeWindowsForever: 0,
            playtimeMacForever: 0,
            playtimeLinuxForever: 0,
            playtimeDeckForever: 0,
            playtimeOffline: 0,
            lastTimePlayed: 0,
            playtime2Weeks: 0,
            iconUrl:
                "https://media.steampowered.com/steamcommunity/public/images/apps/282800/baaf4be38deeb8a631567ee6c651ca23b65c834a.jpg",
        },
        {
            appid: 1507190,
            name: "Machinika Museum",
            playtimeForever: 0,
            playtimeWindowsForever: 0,
            playtimeMacForever: 0,
            playtimeLinuxForever: 0,
            playtimeDeckForever: 0,
            playtimeOffline: 0,
            lastTimePlayed: 0,
            playtime2Weeks: 0,
            iconUrl:
                "https://media.steampowered.com/steamcommunity/public/images/apps/1507190/f4bb2176803e4b08c0da1032ea59d9a995ccff5b.jpg",
        },
        {
            appid: 2962300,
            name: "Royal Quest Online",
            playtimeForever: 0,
            playtimeWindowsForever: 0,
            playtimeMacForever: 0,
            playtimeLinuxForever: 0,
            playtimeDeckForever: 0,
            playtimeOffline: 0,
            lastTimePlayed: 0,
            playtime2Weeks: 0,
            iconUrl:
                "https://media.steampowered.com/steamcommunity/public/images/apps/2962300/c2df557759a85afae63f35337bf64d1d592b1c98.jpg",
        },
        {
            appid: 289130,
            name: "ENDLESS™ Legend",
            playtimeForever: 0,
            playtimeWindowsForever: 0,
            playtimeMacForever: 0,
            playtimeLinuxForever: 0,
            playtimeDeckForever: 0,
            playtimeOffline: 0,
            lastTimePlayed: 0,
            playtime2Weeks: 0,
            iconUrl:
                "https://media.steampowered.com/steamcommunity/public/images/apps/289130/02277be6b9b09671b857948006316057974d7036.jpg",
        },
        {
            appid: 489630,
            name: "Warhammer 40,000: Gladius - Relics of War",
            playtimeForever: 0,
            playtimeWindowsForever: 0,
            playtimeMacForever: 0,
            playtimeLinuxForever: 0,
            playtimeDeckForever: 0,
            playtimeOffline: 0,
            lastTimePlayed: 0,
            playtime2Weeks: 0,
            iconUrl:
                "https://media.steampowered.com/steamcommunity/public/images/apps/489630/ba6ea4fbeec62073763e103450e8aa7c5373d010.jpg",
        },
        {
            appid: 1426210,
            name: "It Takes Two",
            playtimeForever: 0,
            playtimeWindowsForever: 0,
            playtimeMacForever: 0,
            playtimeLinuxForever: 0,
            playtimeDeckForever: 0,
            playtimeOffline: 0,
            lastTimePlayed: 0,
            playtime2Weeks: 0,
            iconUrl:
                "https://media.steampowered.com/steamcommunity/public/images/apps/1426210/6b15f6d81c4fc52056f4928b363b7fac591a945b.jpg",
        },
        {
            appid: 442070,
            name: "Drawful 2",
            playtimeForever: 0,
            playtimeWindowsForever: 0,
            playtimeMacForever: 0,
            playtimeLinuxForever: 0,
            playtimeDeckForever: 0,
            playtimeOffline: 0,
            lastTimePlayed: 0,
            playtime2Weeks: 0,
            iconUrl:
                "https://media.steampowered.com/steamcommunity/public/images/apps/442070/a2aab99a9ec657f817aff247593b3310cae44288.jpg",
        },
        {
            appid: 2828500,
            name: "The Jackbox Megapicker",
            playtimeForever: 0,
            playtimeWindowsForever: 0,
            playtimeMacForever: 0,
            playtimeLinuxForever: 0,
            playtimeDeckForever: 0,
            playtimeOffline: 0,
            lastTimePlayed: 0,
            playtime2Weeks: 0,
            iconUrl:
                "https://media.steampowered.com/steamcommunity/public/images/apps/2828500/0866a1d27e96a96c7d013c41eb6fa2ec6a935a7d.jpg",
        },
        {
            appid: 1422450,
            name: "Deadlock",
            playtimeForever: 518,
            playtimeWindowsForever: 518,
            playtimeMacForever: 0,
            playtimeLinuxForever: 0,
            playtimeDeckForever: 0,
            playtimeOffline: 0,
            lastTimePlayed: 1725278119,
            playtime2Weeks: 0,
            iconUrl:
                "https://media.steampowered.com/steamcommunity/public/images/apps/1422450/f6da1420a173324d49bcd470fa3eee781ad0fa5e.jpg",
        },
        {
            appid: 373600,
            name: "Weapon of Choice",
            playtimeForever: 0,
            playtimeWindowsForever: 0,
            playtimeMacForever: 0,
            playtimeLinuxForever: 0,
            playtimeDeckForever: 0,
            playtimeOffline: 0,
            lastTimePlayed: 0,
            playtime2Weeks: 0,
            iconUrl:
                "https://media.steampowered.com/steamcommunity/public/images/apps/373600/16928dc115d57b622669c96a4d666a47f3023e7a.jpg",
        },
        {
            appid: 569610,
            name: "Distant Space",
            playtimeForever: 0,
            playtimeWindowsForever: 0,
            playtimeMacForever: 0,
            playtimeLinuxForever: 0,
            playtimeDeckForever: 0,
            playtimeOffline: 0,
            lastTimePlayed: 0,
            playtime2Weeks: 0,
            iconUrl:
                "https://media.steampowered.com/steamcommunity/public/images/apps/569610/1cfe852a7e1054108d50d2a3b28219411b776bc4.jpg",
        },
        {
            appid: 3352550,
            name: "Like a Dragon: Pirate Yakuza in Hawaii Demo",
            playtimeForever: 0,
            playtimeWindowsForever: 0,
            playtimeMacForever: 0,
            playtimeLinuxForever: 0,
            playtimeDeckForever: 0,
            playtimeOffline: 0,
            lastTimePlayed: 0,
            playtime2Weeks: 0,
            iconUrl:
                "https://media.steampowered.com/steamcommunity/public/images/apps/3352550/36457865acaa83643207ffad25422f62538b8cbf.jpg",
        },
        {
            appid: 220,
            name: "Half-Life 2",
            playtimeForever: 0,
            playtimeWindowsForever: 0,
            playtimeMacForever: 0,
            playtimeLinuxForever: 0,
            playtimeDeckForever: 0,
            playtimeOffline: 0,
            lastTimePlayed: 0,
            playtime2Weeks: 0,
            iconUrl:
                "https://media.steampowered.com/steamcommunity/public/images/apps/220/fcfb366051782b8ebf2aa297f3b746395858cb62.jpg",
        },
        {
            appid: 320,
            name: "Half-Life 2: Deathmatch",
            playtimeForever: 0,
            playtimeWindowsForever: 0,
            playtimeMacForever: 0,
            playtimeLinuxForever: 0,
            playtimeDeckForever: 0,
            playtimeOffline: 0,
            lastTimePlayed: 0,
            playtime2Weeks: 0,
            iconUrl:
                "https://media.steampowered.com/steamcommunity/public/images/apps/320/795e85364189511f4990861b578084deef086cb1.jpg",
        },
        {
            appid: 360,
            name: "Half-Life Deathmatch: Source",
            playtimeForever: 0,
            playtimeWindowsForever: 0,
            playtimeMacForever: 0,
            playtimeLinuxForever: 0,
            playtimeDeckForever: 0,
            playtimeOffline: 0,
            lastTimePlayed: 0,
            playtime2Weeks: 0,
            iconUrl:
                "https://media.steampowered.com/steamcommunity/public/images/apps/360/40b8a62efff5a9ab356e5c56f5c8b0532c8e1aa3.jpg",
        },
        {
            appid: 29900,
            name: "Dark Sector",
            playtimeForever: 0,
            playtimeWindowsForever: 0,
            playtimeMacForever: 0,
            playtimeLinuxForever: 0,
            playtimeDeckForever: 0,
            playtimeOffline: 0,
            lastTimePlayed: 0,
            playtime2Weeks: 0,
            iconUrl:
                "https://media.steampowered.com/steamcommunity/public/images/apps/29900/e1eede77996260a65a37d3610634ed88a0b6a6db.jpg",
        },
        {
            appid: 418670,
            name: "Pankapu",
            playtimeForever: 0,
            playtimeWindowsForever: 0,
            playtimeMacForever: 0,
            playtimeLinuxForever: 0,
            playtimeDeckForever: 0,
            playtimeOffline: 0,
            lastTimePlayed: 0,
            playtime2Weeks: 0,
            iconUrl:
                "https://media.steampowered.com/steamcommunity/public/images/apps/418670/646b618afcddf400428cb3e77034be3eb1bbbf80.jpg",
        },
        {
            appid: 729460,
            name: "Distant Space 2",
            playtimeForever: 0,
            playtimeWindowsForever: 0,
            playtimeMacForever: 0,
            playtimeLinuxForever: 0,
            playtimeDeckForever: 0,
            playtimeOffline: 0,
            lastTimePlayed: 0,
            playtime2Weeks: 0,
            iconUrl:
                "https://media.steampowered.com/steamcommunity/public/images/apps/729460/0c9c34d2e426d9086b95c7034a12981220a541ee.jpg",
        },
        {
            appid: 481870,
            name: "Mini Thief",
            playtimeForever: 0,
            playtimeWindowsForever: 0,
            playtimeMacForever: 0,
            playtimeLinuxForever: 0,
            playtimeDeckForever: 0,
            playtimeOffline: 0,
            lastTimePlayed: 0,
            playtime2Weeks: 0,
            iconUrl:
                "https://media.steampowered.com/steamcommunity/public/images/apps/481870/80df03476ae26bb8b20df00e5de0acc1fbb1792a.jpg",
        },
        {
            appid: 1703140,
            name: "Isle of Jura",
            playtimeForever: 0,
            playtimeWindowsForever: 0,
            playtimeMacForever: 0,
            playtimeLinuxForever: 0,
            playtimeDeckForever: 0,
            playtimeOffline: 0,
            lastTimePlayed: 0,
            playtime2Weeks: 0,
            iconUrl:
                "https://media.steampowered.com/steamcommunity/public/images/apps/1703140/56e2dd9001f5ec270f01115af28f47d8cd9bcbb1.jpg",
        },
        {
            appid: 2796010,
            name: "Party Club",
            playtimeForever: 0,
            playtimeWindowsForever: 0,
            playtimeMacForever: 0,
            playtimeLinuxForever: 0,
            playtimeDeckForever: 0,
            playtimeOffline: 0,
            lastTimePlayed: 0,
            playtime2Weeks: 0,
            iconUrl:
                "https://media.steampowered.com/steamcommunity/public/images/apps/2796010/a80c96dde162ef5ed25704384b6e312b6b6cddf9.jpg",
        },
        {
            appid: 813540,
            name: "Scheming Through The Zombie Apocalypse: The Beginning",
            playtimeForever: 0,
            playtimeWindowsForever: 0,
            playtimeMacForever: 0,
            playtimeLinuxForever: 0,
            playtimeDeckForever: 0,
            playtimeOffline: 0,
            lastTimePlayed: 0,
            playtime2Weeks: 0,
            iconUrl:
                "https://media.steampowered.com/steamcommunity/public/images/apps/813540/3138e1c654922fd57f59f91e6579a975aabc4ecc.jpg",
        },
        {
            appid: 302190,
            name: "Amerzone: The Explorer’s Legacy (1999)",
            playtimeForever: 0,
            playtimeWindowsForever: 0,
            playtimeMacForever: 0,
            playtimeLinuxForever: 0,
            playtimeDeckForever: 0,
            playtimeOffline: 0,
            lastTimePlayed: 0,
            playtime2Weeks: 0,
            iconUrl:
                "https://media.steampowered.com/steamcommunity/public/images/apps/302190/d6ff9aa52c570e15342b487a6048539bdb182074.jpg",
        },
        {
            appid: 753660,
            name: "AtmaSphere",
            playtimeForever: 0,
            playtimeWindowsForever: 0,
            playtimeMacForever: 0,
            playtimeLinuxForever: 0,
            playtimeDeckForever: 0,
            playtimeOffline: 0,
            lastTimePlayed: 0,
            playtime2Weeks: 0,
            iconUrl:
                "https://media.steampowered.com/steamcommunity/public/images/apps/753660/0f3559c8e03858f975a1d2ab7dfb7a06a60d06de.jpg",
        },
        {
            appid: 252410,
            name: "SteamWorld Dig",
            playtimeForever: 0,
            playtimeWindowsForever: 0,
            playtimeMacForever: 0,
            playtimeLinuxForever: 0,
            playtimeDeckForever: 0,
            playtimeOffline: 0,
            lastTimePlayed: 0,
            playtime2Weeks: 0,
            iconUrl:
                "https://media.steampowered.com/steamcommunity/public/images/apps/252410/7757c90bbf65e312ea4871106250077e78007bc6.jpg",
        },
        {
            appid: 1608450,
            name: "Hellslave",
            playtimeForever: 0,
            playtimeWindowsForever: 0,
            playtimeMacForever: 0,
            playtimeLinuxForever: 0,
            playtimeDeckForever: 0,
            playtimeOffline: 0,
            lastTimePlayed: 0,
            playtime2Weeks: 0,
            iconUrl:
                "https://media.steampowered.com/steamcommunity/public/images/apps/1608450/733a62d2f790189f9cecb01bebf8e014a231a86e.jpg",
        },
        {
            appid: 624690,
            name: "NEXT JUMP: Shmup Tactics",
            playtimeForever: 0,
            playtimeWindowsForever: 0,
            playtimeMacForever: 0,
            playtimeLinuxForever: 0,
            playtimeDeckForever: 0,
            playtimeOffline: 0,
            lastTimePlayed: 0,
            playtime2Weeks: 0,
            iconUrl:
                "https://media.steampowered.com/steamcommunity/public/images/apps/624690/c31aa58c0d3f7ccfbf99bfd81918e4767641be82.jpg",
        },
        {
            appid: 1356040,
            name: "Ampersat",
            playtimeForever: 0,
            playtimeWindowsForever: 0,
            playtimeMacForever: 0,
            playtimeLinuxForever: 0,
            playtimeDeckForever: 0,
            playtimeOffline: 0,
            lastTimePlayed: 0,
            playtime2Weeks: 0,
            iconUrl:
                "https://media.steampowered.com/steamcommunity/public/images/apps/1356040/82967694d0c9a66be7e0675550b68c74f1c34ffa.jpg",
        },
        {
            appid: 1990740,
            name: "Barro GT",
            playtimeForever: 0,
            playtimeWindowsForever: 0,
            playtimeMacForever: 0,
            playtimeLinuxForever: 0,
            playtimeDeckForever: 0,
            playtimeOffline: 0,
            lastTimePlayed: 0,
            playtime2Weeks: 0,
            iconUrl:
                "https://media.steampowered.com/steamcommunity/public/images/apps/1990740/5bcb2a24d4a2bba21d4ce58a6c236efcd5a9492c.jpg",
        },
        {
            appid: 2955840,
            name: "Kitchen Wars",
            playtimeForever: 0,
            playtimeWindowsForever: 0,
            playtimeMacForever: 0,
            playtimeLinuxForever: 0,
            playtimeDeckForever: 0,
            playtimeOffline: 0,
            lastTimePlayed: 0,
            playtime2Weeks: 0,
            iconUrl:
                "https://media.steampowered.com/steamcommunity/public/images/apps/2955840/93c637e395897e6a681db87bd6ada2371772e4eb.jpg",
        },
        {
            appid: 570,
            name: "Dota 2",
            playtimeForever: 573,
            playtimeWindowsForever: 573,
            playtimeMacForever: 0,
            playtimeLinuxForever: 0,
            playtimeDeckForever: 0,
            playtimeOffline: 0,
            lastTimePlayed: 1742846453,
            playtime2Weeks: 0,
            iconUrl:
                "https://media.steampowered.com/steamcommunity/public/images/apps/570/0bbb630d63262dd66d2fdd0f7d37e8661a410075.jpg",
        },
    ],
    inventories: {
        "570": [
            {
                classid: "329943375",
                instanceid: "782509058",
                marketHashName: "Foreteller's Adorn",
                name: "Foreteller's Adorn",
                type: "Rare Skirt",
                tradable: false,
                marketable: false,
                commodity: false,
                iconUrl:
                    "https://steamcommunity-a.akamaihd.net/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttydbPaERSR0Wqmu7LAocGIyi3kajH_LRwt6pCmuF6kZ98ZO77Fb1RAn0kprl7x1X6vW9J6JiMvWHC2ucxPxJvORuXGfrwUolsDzXmY2pdy2VaFQnCZsjTbMItEOxltPnZLnr4FDfg4JAyCz7kGoXuR1irGL0",
                marketUrl:
                    "https://steamcommunity.com/market/listings/570/Foreteller's%20Adorn",
                extra: {
                    appid: 570,
                    currency: 0,
                    background_color: "",
                    icon_url_large:
                        "i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttydbPaERSR0Wqmu7LAocGIyi3kajH_LRwt6pCmuF6kZ98ZO77Fb1RAn0kprl7x1X6vW9J6JiMvWHC2ucxPxJvORuXBa_lA8gtnOEzNehcC2TalByC5R0RONcsxe_loWyM-vm7gXW2d8WyHn4jihIvHlr_a9cBrwFISqR",
                    descriptions: [
                        {
                            type: "html",
                            value: "Used By: Death Prophet",
                            name: "attribute",
                        },
                        {
                            type: "html",
                            value: " ",
                            name: "attribute",
                        },
                        {
                            type: "html",
                            value: "Foreteller's Robes",
                            color: "9da1a9",
                            name: "attribute",
                        },
                        {
                            type: "html",
                            value: "Foreteller's Haircomb",
                            color: "6c7075",
                            name: "attribute",
                        },
                        {
                            type: "html",
                            value: "Foreteller's Garment",
                            color: "6c7075",
                            name: "attribute",
                        },
                        {
                            type: "html",
                            value: "Foreteller's Drapes",
                            color: "6c7075",
                            name: "attribute",
                        },
                        {
                            type: "html",
                            value: "Foreteller's Adorn",
                            color: "6c7075",
                            name: "attribute",
                        },
                        {
                            type: "html",
                            value: " ",
                            name: "attribute",
                        },
                        {
                            type: "html",
                            value: "( Not Tradable )",
                            name: "attribute",
                        },
                        {
                            type: "html",
                            value: "( This item may be gifted once )",
                            name: "attribute",
                        },
                    ],
                    name_color: "D2D2D2",
                    market_name: "Foreteller's Adorn",
                    market_tradable_restriction: 7,
                    market_marketable_restriction: 0,
                    tags: [
                        {
                            category: "Quality",
                            internal_name: "unique",
                            localized_category_name: "Quality",
                            localized_tag_name: "Standard",
                            color: "D2D2D2",
                        },
                        {
                            category: "Rarity",
                            internal_name: "Rarity_Rare",
                            localized_category_name: "Rarity",
                            localized_tag_name: "Rare",
                            color: "4b69ff",
                        },
                        {
                            category: "Type",
                            internal_name: "wearable",
                            localized_category_name: "Type",
                            localized_tag_name: "Wearable",
                        },
                        {
                            category: "Slot",
                            internal_name: "legs",
                            localized_category_name: "Slot",
                            localized_tag_name: "Legs",
                        },
                        {
                            category: "Hero",
                            internal_name:
                                "npc_dota_hero_death_prophet",
                            localized_category_name: "Hero",
                            localized_tag_name: "Death Prophet",
                        },
                    ],
                    sealed: 0,
                },
            },
            {
                classid: "4672396955",
                instanceid: "1625510296",
                marketHashName:
                    "Carnage of the Endless Hunt - Shoulders",
                name: "Carnage of the Endless Hunt - Shoulders",
                type: "Mythical armor",
                tradable: true,
                marketable: true,
                commodity: false,
                iconUrl:
                    "https://steamcommunity-a.akamaihd.net/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttydbPaERSR0Wqmu7LAocGIyi3kajH_fMxoWgMnOE50ZKptemu2bmWRjOjZ7v6C5f6uC9V7I_b_GUBnSS0dEk4LM4cCirkCI0uzKQlov8Mzj4KAQ-DcBzRLVctEO8x4ayPuKztADajN9Aznitj3tKvHti4uZTAKdwqPCB2haBb-On5Dcocw",
                marketUrl:
                    "https://steamcommunity.com/market/listings/570/Carnage%20of%20the%20Endless%20Hunt%20-%20Shoulders",
                extra: {
                    appid: 570,
                    currency: 0,
                    background_color: "",
                    icon_url_large:
                        "i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttydbPaERSR0Wqmu7LAocGIyi3kajH_fMxoWgMnOE50ZKptemu2bmWRjOjZ7v6C5f6uC9V7I_b_GUBnSS0dEk4LM4cCirkCI0uzKQlov8Mzj4KARPVsMyErIU4UG6w4G0NL624wXbg4MRzCT8j35Iv3pste5TU6MgrqfUjgDFML0_t45DeqguXZhP8w",
                    descriptions: [
                        {
                            type: "html",
                            value: "Used By: Axe",
                            name: "attribute",
                        },
                        {
                            type: "html",
                            value: " ",
                            name: "attribute",
                        },
                        {
                            type: "html",
                            value: "Carnage of the Endless Hunt",
                            color: "9da1a9",
                            name: "attribute",
                        },
                        {
                            type: "html",
                            value: "Carnage of the Endless Hunt - Head",
                            color: "6c7075",
                            name: "attribute",
                        },
                        {
                            type: "html",
                            value: "Carnage of the Endless Hunt - Belt",
                            color: "6c7075",
                            name: "attribute",
                        },
                        {
                            type: "html",
                            value: "Carnage of the Endless Hunt - Weapon",
                            color: "6c7075",
                            name: "attribute",
                        },
                        {
                            type: "html",
                            value: "Carnage of the Endless Hunt - Shoulders",
                            color: "6c7075",
                            name: "attribute",
                        },
                    ],
                    name_color: "D2D2D2",
                    market_name:
                        "Carnage of the Endless Hunt - Shoulders",
                    market_tradable_restriction: 7,
                    market_marketable_restriction: 0,
                    tags: [
                        {
                            category: "Quality",
                            internal_name: "unique",
                            localized_category_name: "Quality",
                            localized_tag_name: "Standard",
                            color: "D2D2D2",
                        },
                        {
                            category: "Rarity",
                            internal_name: "Rarity_Mythical",
                            localized_category_name: "Rarity",
                            localized_tag_name: "Mythical",
                            color: "8847ff",
                        },
                        {
                            category: "Type",
                            internal_name: "wearable",
                            localized_category_name: "Type",
                            localized_tag_name: "Wearable",
                        },
                        {
                            category: "Slot",
                            internal_name: "armor",
                            localized_category_name: "Slot",
                            localized_tag_name: "Armor",
                        },
                        {
                            category: "Hero",
                            internal_name: "npc_dota_hero_axe",
                            localized_category_name: "Hero",
                            localized_tag_name: "Axe",
                        },
                    ],
                    sealed: 0,
                },
            },
        ],
        "730": [
            {
                classid: "310776672",
                instanceid: "302028390",
                marketHashName: "SCAR-20 | Sand Mesh (Field-Tested)",
                name: "SCAR-20 | Sand Mesh",
                type: "Consumer Grade Sniper Rifle",
                tradable: true,
                marketable: true,
                commodity: false,
                iconUrl:
                    "https://steamcommunity-a.akamaihd.net/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu5Dx60noTyLinZfyr3Jk_OKRZaF-KM-AD2mU_uNztOh8Qmfhx05-5m_TzNmrIn2XOlBxXpRwE-MDtUa-k4WxYejg4lOPiN1NnCivkGoXufVRJln-",
                marketUrl:
                    "https://steamcommunity.com/market/listings/730/SCAR-20%20%7C%20Sand%20Mesh%20(Field-Tested)",
                extra: {
                    appid: 730,
                    currency: 0,
                    background_color: "",
                    descriptions: [
                        {
                            type: "html",
                            value: "Exterior: Field-Tested",
                            name: "exterior_wear",
                        },
                        {
                            type: "html",
                            value: " ",
                            name: "blank",
                        },
                        {
                            type: "html",
                            value: "The SCAR-20 is a semi-automatic sniper rifle that trades a high rate of fire and powerful long-distance damage for sluggish movement speed and big price tag. It has been spray-painted using mesh fencing and cardboard cutouts as stencils.\n\n<i>A predator is a predator, no matter the environment</i>",
                            name: "description",
                        },
                        {
                            type: "html",
                            value: " ",
                            name: "blank",
                        },
                        {
                            type: "html",
                            value: "The Dust 2 Collection",
                            color: "9da1a9",
                            name: "itemset_name",
                        },
                        {
                            type: "html",
                            value: " ",
                            name: "blank",
                        },
                    ],
                    actions: [
                        {
                            link: "steam://rungame/730/76561202255233023/+csgo_econ_action_preview%20S%owner_steamid%A%assetid%D180254498501304692",
                            name: "Inspect in Game...",
                        },
                    ],
                    name_color: "D2D2D2",
                    market_name: "SCAR-20 | Sand Mesh (Field-Tested)",
                    market_actions: [
                        {
                            link: "steam://rungame/730/76561202255233023/+csgo_econ_action_preview%20M%listingid%A%assetid%D180254498501304692",
                            name: "Inspect in Game...",
                        },
                    ],
                    market_tradable_restriction: 7,
                    market_marketable_restriction: 7,
                    tags: [
                        {
                            category: "Type",
                            internal_name: "CSGO_Type_SniperRifle",
                            localized_category_name: "Type",
                            localized_tag_name: "Sniper Rifle",
                        },
                        {
                            category: "Weapon",
                            internal_name: "weapon_scar20",
                            localized_category_name: "Weapon",
                            localized_tag_name: "SCAR-20",
                        },
                        {
                            category: "ItemSet",
                            internal_name: "set_dust_2",
                            localized_category_name: "Collection",
                            localized_tag_name: "The Dust 2 Collection",
                        },
                        {
                            category: "Quality",
                            internal_name: "normal",
                            localized_category_name: "Category",
                            localized_tag_name: "Normal",
                        },
                        {
                            category: "Rarity",
                            internal_name: "Rarity_Common_Weapon",
                            localized_category_name: "Quality",
                            localized_tag_name: "Consumer Grade",
                            color: "b0c3d9",
                        },
                        {
                            category: "Exterior",
                            internal_name: "WearCategory2",
                            localized_category_name: "Exterior",
                            localized_tag_name: "Field-Tested",
                        },
                    ],
                    sealed: 0,
                },
            },
            {
                classid: "5710094579",
                instanceid: "302028390",
                marketHashName: "Kilowatt Case",
                name: "Kilowatt Case",
                type: "Base Grade Container",
                tradable: true,
                marketable: true,
                commodity: true,
                iconUrl:
                    "https://steamcommunity-a.akamaihd.net/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGJKz2lu_XsnXwtmkJjSU91dh8bj35VTqVBP4io_frnEVvqf_a6VoIfGSXz7Hlbwg57QwSS_mxhl15jiGyN37c3_GZw91W8BwRflK7EfKsa2sfw",
                marketUrl:
                    "https://steamcommunity.com/market/listings/730/Kilowatt%20Case",
                extra: {
                    appid: 730,
                    currency: 0,
                    background_color: "",
                    descriptions: [
                        {
                            type: "html",
                            value: " ",
                            name: "blank",
                        },
                        {
                            type: "html",
                            value: "Items in this container can be rented.",
                            name: "attr: can open for rental",
                        },
                        {
                            type: "html",
                            value: "Container Series #393",
                            color: "99ccff",
                            name: "attr: set supply crate series",
                        },
                        {
                            type: "html",
                            value: " ",
                            name: "blank",
                        },
                        {
                            type: "html",
                            value: "Contains one of the following:",
                            name: "attribute",
                        },
                        {
                            type: "html",
                            value: "Dual Berettas | Hideout",
                            color: "4b69ff",
                            name: "attribute",
                        },
                        {
                            type: "html",
                            value: "MAC-10 | Light Box",
                            color: "4b69ff",
                            name: "attribute",
                        },
                        {
                            type: "html",
                            value: "Nova | Dark Sigil",
                            color: "4b69ff",
                            name: "attribute",
                        },
                        {
                            type: "html",
                            value: "SSG 08 | Dezastre",
                            color: "4b69ff",
                            name: "attribute",
                        },
                        {
                            type: "html",
                            value: "Tec-9 | Slag",
                            color: "4b69ff",
                            name: "attribute",
                        },
                        {
                            type: "html",
                            value: "UMP-45 | Motorized",
                            color: "4b69ff",
                            name: "attribute",
                        },
                        {
                            type: "html",
                            value: "XM1014 | Irezumi",
                            color: "4b69ff",
                            name: "attribute",
                        },
                        {
                            type: "html",
                            value: "Glock-18 | Block-18",
                            color: "8847ff",
                            name: "attribute",
                        },
                        {
                            type: "html",
                            value: "M4A4 | Etch Lord",
                            color: "8847ff",
                            name: "attribute",
                        },
                        {
                            type: "html",
                            value: "Five-SeveN | Hybrid",
                            color: "8847ff",
                            name: "attribute",
                        },
                        {
                            type: "html",
                            value: "MP7 | Just Smile",
                            color: "8847ff",
                            name: "attribute",
                        },
                        {
                            type: "html",
                            value: "Sawed-Off | Analog Input",
                            color: "8847ff",
                            name: "attribute",
                        },
                        {
                            type: "html",
                            value: "M4A1-S | Black Lotus",
                            color: "d32ce6",
                            name: "attribute",
                        },
                        {
                            type: "html",
                            value: "Zeus x27 | Olympus",
                            color: "d32ce6",
                            name: "attribute",
                        },
                        {
                            type: "html",
                            value: "USP-S | Jawbreaker",
                            color: "d32ce6",
                            name: "attribute",
                        },
                        {
                            type: "html",
                            value: "AWP | Chrome Cannon",
                            color: "eb4b4b",
                            name: "attribute",
                        },
                        {
                            type: "html",
                            value: "AK-47 | Inheritance",
                            color: "eb4b4b",
                            name: "attribute",
                        },
                        {
                            type: "html",
                            value: "or an Exceedingly Rare Kukri Knife!",
                            color: "ffd700",
                            name: "attribute",
                        },
                        {
                            type: "html",
                            value: " ",
                            name: "blank",
                        },
                        {
                            type: "html",
                            value: "",
                            color: "00a000",
                            name: "attribute",
                        },
                    ],
                    name_color: "D2D2D2",
                    market_name: "Kilowatt Case",
                    market_tradable_restriction: 7,
                    market_marketable_restriction: 7,
                    tags: [
                        {
                            category: "Type",
                            internal_name: "CSGO_Type_WeaponCase",
                            localized_category_name: "Type",
                            localized_tag_name: "Container",
                        },
                        {
                            category: "ItemSet",
                            internal_name: "set_community_33",
                            localized_category_name: "Collection",
                            localized_tag_name:
                                "The Kilowatt Collection",
                        },
                        {
                            category: "Quality",
                            internal_name: "normal",
                            localized_category_name: "Category",
                            localized_tag_name: "Normal",
                        },
                        {
                            category: "Rarity",
                            internal_name: "Rarity_Common",
                            localized_category_name: "Quality",
                            localized_tag_name: "Base Grade",
                            color: "b0c3d9",
                        },
                    ],
                    sealed: 0,
                },
            },
        ],
        "753": [
            {
                classid: "5659557100",
                instanceid: "3873495864",
                marketHashName: "2640280-Steam Winter Evening 2023",
                name: "Steam Winter Evening 2023",
                type: "Winter Sale 2023 Profile Modifier",
                tradable: false,
                marketable: false,
                commodity: true,
                iconUrl:
                    "https://steamcommunity-a.akamaihd.net/economy/image/a0b44yVZG6xneuQqGEgxNyzAxlmouy8Ipo0bUlJjRDfF9dQS1eD3AHU-t8xnioHyGdqSZpgsmMIM6FMEcwCVUaI-oVdii0gFynPfOMS4FqOQ82it_thRR6Pc4uD8iMO1-XRTiM19Pt8eLNXp-eqiwkvuVw8",
                marketUrl:
                    "https://steamcommunity.com/market/listings/753/2640280-Steam%20Winter%20Evening%202023",
                extra: {
                    appid: 753,
                    currency: 0,
                    background_color: "",
                    icon_url_large:
                        "a0b44yVZG6xneuQqGEgxNyzAxlmouy8Ipo0bUlJjRDfF9dQS1eD3AHU-t8xnioHyGdqSZpgsmMIM6FMEcwCVUaI-oVJujxZXk3mNacTtQKLD9D__-dRVEfDZuLCmipC0qnIGiccjboUUI9Xp-eqi4LK4Yh8",
                    descriptions: [
                        {
                            value: "Art and animation by Waneella",
                        },
                    ],
                    market_name: "Steam Winter Evening 2023",
                    market_fee_app: 2640280,
                    market_tradable_restriction: 7,
                    market_marketable_restriction: 7,
                    tags: [
                        {
                            category: "droprate",
                            internal_name: "droprate_0",
                            localized_category_name: "Rarity",
                            localized_tag_name: "Common",
                        },
                        {
                            category: "Game",
                            internal_name: "app_2640280",
                            localized_category_name: "Game",
                            localized_tag_name: "Winter Sale 2023",
                        },
                        {
                            category: "Event",
                            internal_name: "wintersale2023",
                            localized_category_name: "Event",
                            localized_tag_name: "Winter Sale 2023",
                        },
                        {
                            category: "item_class",
                            internal_name: "item_class_8",
                            localized_category_name: "Item Type",
                            localized_tag_name: "Profile Modifier",
                        },
                    ],
                    sealed: 0,
                },
            },
            {
                classid: "149754772",
                instanceid: "246376127",
                marketHashName: "730-FBI",
                name: "FBI",
                type: "Counter-Strike 2 Trading Card",
                tradable: true,
                marketable: true,
                commodity: true,
                iconUrl:
                    "https://steamcommunity-a.akamaihd.net/economy/image/IzMF03bk9WpSBq-S-ekoE33L-iLqGFHVaU25ZzQNQcXdA3g5gMEPvUZZEfSMJ6dESN8p_2SVTY7V2N4MxGVIwXpaL3_e_10rbOhtP86bwQH-9LqLSyH1P2GSeCfcRA0wT-ALZGnYqzug7L6TFjubRLkqQwEAfLxErDNfb5bLa0d_u95WqmK9ykF5RhN9I5FFcg3tmHVLMLxxySJBd85anXf2Jp2NhQ1hOhU8Xe3kVbzcL9_yhmkpX5t2C6_O",
                marketUrl:
                    "https://steamcommunity.com/market/listings/753/730-FBI",
                extra: {
                    appid: 753,
                    currency: 0,
                    background_color: "",
                    icon_url_large:
                        "IzMF03bk9WpSBq-S-ekoE33L-iLqGFHVaU25ZzQNQcXdA3g5gMEPvUZZEfSMJ6dESN8p_2SVTY7V2N4MxGVIwXpaL3_e_10rbOhtP86bwQH-9LqLSyH1P2GSeCfcRA0wT-ALZGnYqzug7L6TFjubRLkqQwEAfLxErDNfb5bLa0d_u95WqmK9ykF5RhN9I5FFcg3tmHVLMLxxySJBd85anXf2Jp2NhQ1hOhU8Xe3kVbzcL9_yhmkpX5t2C6_O",
                    descriptions: [
                        {
                            value: "",
                        },
                    ],
                    market_name: "FBI",
                    market_fee_app: 730,
                    market_tradable_restriction: 7,
                    market_marketable_restriction: 7,
                    tags: [
                        {
                            category: "droprate",
                            internal_name: "droprate_0",
                            localized_category_name: "Rarity",
                            localized_tag_name: "Common",
                        },
                        {
                            category: "Game",
                            internal_name: "app_730",
                            localized_category_name: "Game",
                            localized_tag_name: "Counter-Strike 2",
                        },
                        {
                            category: "cardborder",
                            internal_name: "cardborder_0",
                            localized_category_name: "Card Border",
                            localized_tag_name: "Normal",
                        },
                        {
                            category: "item_class",
                            internal_name: "item_class_2",
                            localized_category_name: "Item Type",
                            localized_tag_name: "Trading Card",
                        },
                    ],
                    sealed: 0,
                },
            },
        ],
    },
}